apiVersion: v1
kind: Pod
metadata:
  name: laravel 
  labels:
    app: laravel
spec:
  containers:
  - name: cont1
    image: laravelfans/laravel
    ports:
      - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: mynodeport
spec:
  selector: 
    app: laravel
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 32001
