apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jhooq-laravel
  template:
    metadata:
      labels:
        app: jhooq-laravel
    spec:
      containers:
        - name: laravel
          image: baladoc2023/final
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: jhooq-laravel
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: jhooq-laravel
