apiVersion: v1
kind: Pod
metadata:
  name: laravel
  labels:
    app:  myapp
spec:
  containers:
  - name: laravel
    image: baladoc2023/final
    ports:
    - containerPort: 8081

---


kind: Service
apiVersion: v1
metadata:
  name:  mynodeport
spec:
  selector:
    app:  myapp
  type:  NodePort
  ports:
  - name:  httpd
    port:  80
    targetPort:  8081
    protocol: TCP
